
// Generated by MyGeneration Version # (1.1.3.5)

using System;

namespace MyGeneration.dOOdads.Tests.SQLite
{
	public class AggregateTest : _AggregateTest
	{
		public AggregateTest()
		{
		
		}
	}
}
