
// Generated by MyGeneration Version # (1.1.4.0)

using System;

namespace MyGeneration.dOOdads.Tests.SQL
{
	public class AggregateTest : _AggregateTest
	{
		public AggregateTest()
		{
		
		}
	}
}
