
// Generated by MyGeneration Version # (1.1.3.0)

using System;

namespace MyGeneration.dOOdads.Tests.SQL
{
	public class FullNameView : _FullNameView
	{
		public FullNameView()
		{
		
		}
	}
}
