
' Generated by MyGeneration Version # (1.0.0.4)
Namespace SQL
    Public Class Employees
        Inherits _Employees

        Public Function TestQuery() As Integer
            Return Me.LoadFromSqlScalar("proc_SampleQuery")
        End Function

    End Class
End Namespace
