CREATE TABLE "MYGENERATION"."AGGREGATETEST" 
( 
	"ID" NUMBER, 
	"DEPARTMENTID" NUMBER, 
	"FIRSTNAME" VARCHAR2(25), 
	"LASTNAME" VARCHAR2(15), 
	"AGE" NUMBER, 
	"HIREDATE" DATE, 
	"SALARY" NUMBER(8, 4), 
	"ISACTIVE" NUMBER(2), 
	CHECK ("ID" IS NOT NULL) VALIDATE , 
	PRIMARY KEY ("ID") VALIDATE 
) 
TABLESPACE "SYSTEM" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE 
( INITIAL 64K FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT ) 
LOGGING 