
// Generated by MyGeneration Version # (1.1.3.0)

using System;

namespace MyGeneration.dOOdads.Tests.Oracle
{
	public class AggregateTest : _AGGREGATETEST
	{
		public AggregateTest()
		{
		
		}
	}
}
