
/*
'===============================================================================
'  Generated From - SQLite_CSharp_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
' THIS CODE IS NOT OPERATIONAL YET
'===============================================================================
*/

// Generated by MyGeneration Version # (1.1.0.0)

using System;
using System.Data;
using Finisar.SQLite;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace CSharp.SQLite
{
	public abstract class _Employees : SQLiteEntity
	{
		public _Employees()
		{
			this.QuerySource = "Employees";
			this.MappingName = "Employees";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
		}
		
		public override void FlushData()
		{
			this._whereClause = null;
			base.FlushData();
		}
		
		public override string GetAutoKeyColumns()
		{
			return "EmployeeID";
		}
		

		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			return this.Query.Load();
		}
	
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(long EmployeeID)
		{
			this.Where.EmployeeID.Value = EmployeeID;
			
			return this.Query.Load();
		}
		
		
		#region Parameters
		protected class Parameters
		{
			
			public static SQLiteParameter EmployeeID
			{
				get
				{
					return new SQLiteParameter("@EmployeeID", DbType.Int64);

				}
			}
			
			public static SQLiteParameter LastName
			{
				get
				{
					return new SQLiteParameter("@LastName", DbType.String);

				}
			}
			
			public static SQLiteParameter FirstName
			{
				get
				{
					return new SQLiteParameter("@FirstName", DbType.String);

				}
			}
			
			public static SQLiteParameter MYINTEGER
			{
				get
				{
					return new SQLiteParameter("@MYINTEGER", DbType.Int64);

				}
			}
			
			public static SQLiteParameter MYINT
			{
				get
				{
					return new SQLiteParameter("@MYINT", DbType.Int32);

				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
			public const string EmployeeID = "EmployeeID";
			public const string LastName = "LastName";
			public const string FirstName = "FirstName";
			public const string MYINTEGER = "MYINTEGER";
			public const string MYINT = "MYINT";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[EmployeeID] = _Employees.PropertyNames.EmployeeID;
					ht[LastName] = _Employees.PropertyNames.LastName;
					ht[FirstName] = _Employees.PropertyNames.FirstName;
					ht[MYINTEGER] = _Employees.PropertyNames.MYINTEGER;
					ht[MYINT] = _Employees.PropertyNames.MYINT;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
			public const string EmployeeID = "EmployeeID";
			public const string LastName = "LastName";
			public const string FirstName = "FirstName";
			public const string MYINTEGER = "MYINTEGER";
			public const string MYINT = "MYINT";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[EmployeeID] = _Employees.ColumnNames.EmployeeID;
					ht[LastName] = _Employees.ColumnNames.LastName;
					ht[FirstName] = _Employees.ColumnNames.FirstName;
					ht[MYINTEGER] = _Employees.ColumnNames.MYINTEGER;
					ht[MYINT] = _Employees.ColumnNames.MYINT;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
			public const string EmployeeID = "s_EmployeeID";
			public const string LastName = "s_LastName";
			public const string FirstName = "s_FirstName";
			public const string MYINTEGER = "s_MYINTEGER";
			public const string MYINT = "s_MYINT";

		}
		#endregion		
		
		#region Properties
	
		public virtual long EmployeeID
		{
			get
			{
				return base.Getlong(ColumnNames.EmployeeID);
			}
			set
			{
				base.Setlong(ColumnNames.EmployeeID, value);
			}
		}

		public virtual string LastName
		{
			get
			{
				return base.Getstring(ColumnNames.LastName);
			}
			set
			{
				base.Setstring(ColumnNames.LastName, value);
			}
		}

		public virtual string FirstName
		{
			get
			{
				return base.Getstring(ColumnNames.FirstName);
			}
			set
			{
				base.Setstring(ColumnNames.FirstName, value);
			}
		}

		public virtual long MYINTEGER
		{
			get
			{
				return base.Getlong(ColumnNames.MYINTEGER);
			}
			set
			{
				base.Setlong(ColumnNames.MYINTEGER, value);
			}
		}

		public virtual long MYINT
		{
			get
			{
				return base.Getlong(ColumnNames.MYINT);
			}
			set
			{
				base.Setlong(ColumnNames.MYINT, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_EmployeeID
		{
			get
			{
				return this.IsColumnNull(ColumnNames.EmployeeID) ? string.Empty : base.GetlongAsString(ColumnNames.EmployeeID);
			}
			set
			{
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.EmployeeID);
				else
					this.EmployeeID = base.SetlongAsString(ColumnNames.EmployeeID, value);
			}
		}

		public virtual string s_LastName
		{
			get
			{
				return this.IsColumnNull(ColumnNames.LastName) ? string.Empty : base.GetstringAsString(ColumnNames.LastName);
			}
			set
			{
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.LastName);
				else
					this.LastName = base.SetstringAsString(ColumnNames.LastName, value);
			}
		}

		public virtual string s_FirstName
		{
			get
			{
				return this.IsColumnNull(ColumnNames.FirstName) ? string.Empty : base.GetstringAsString(ColumnNames.FirstName);
			}
			set
			{
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.FirstName);
				else
					this.FirstName = base.SetstringAsString(ColumnNames.FirstName, value);
			}
		}

		public virtual string s_MYINTEGER
		{
			get
			{
				return this.IsColumnNull(ColumnNames.MYINTEGER) ? string.Empty : base.GetlongAsString(ColumnNames.MYINTEGER);
			}
			set
			{
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.MYINTEGER);
				else
					this.MYINTEGER = base.SetlongAsString(ColumnNames.MYINTEGER, value);
			}
		}

		public virtual string s_MYINT
		{
			get
			{
				return this.IsColumnNull(ColumnNames.MYINT) ? string.Empty : base.GetlongAsString(ColumnNames.MYINT);
			}
			set
			{
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.MYINT);
				else
					this.MYINT = base.SetlongAsString(ColumnNames.MYINT, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter EmployeeID
				{
					get
					{
						WhereParameter where = new WhereParameter(ColumnNames.EmployeeID, Parameters.EmployeeID);
						this._clause._entity.Query.AddWhereParameter(where);
						return where;
					}
				}

				public WhereParameter LastName
				{
					get
					{
						WhereParameter where = new WhereParameter(ColumnNames.LastName, Parameters.LastName);
						this._clause._entity.Query.AddWhereParameter(where);
						return where;
					}
				}

				public WhereParameter FirstName
				{
					get
					{
						WhereParameter where = new WhereParameter(ColumnNames.FirstName, Parameters.FirstName);
						this._clause._entity.Query.AddWhereParameter(where);
						return where;
					}
				}

				public WhereParameter MYINTEGER
				{
					get
					{
						WhereParameter where = new WhereParameter(ColumnNames.MYINTEGER, Parameters.MYINTEGER);
						this._clause._entity.Query.AddWhereParameter(where);
						return where;
					}
				}

				public WhereParameter MYINT
				{
					get
					{
						WhereParameter where = new WhereParameter(ColumnNames.MYINT, Parameters.MYINT);
						this._clause._entity.Query.AddWhereParameter(where);
						return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter EmployeeID
			{
				get
				{
					if(_EmployeeID_W == null)
					{
						_EmployeeID_W = TearOff.EmployeeID;
					}
					return _EmployeeID_W;
				}
			}

			public WhereParameter LastName
			{
				get
				{
					if(_LastName_W == null)
					{
						_LastName_W = TearOff.LastName;
					}
					return _LastName_W;
				}
			}

			public WhereParameter FirstName
			{
				get
				{
					if(_FirstName_W == null)
					{
						_FirstName_W = TearOff.FirstName;
					}
					return _FirstName_W;
				}
			}

			public WhereParameter MYINTEGER
			{
				get
				{
					if(_MYINTEGER_W == null)
					{
						_MYINTEGER_W = TearOff.MYINTEGER;
					}
					return _MYINTEGER_W;
				}
			}

			public WhereParameter MYINT
			{
				get
				{
					if(_MYINT_W == null)
					{
						_MYINT_W = TearOff.MYINT;
					}
					return _MYINT_W;
				}
			}

			private WhereParameter _EmployeeID_W = null;
			private WhereParameter _LastName_W = null;
			private WhereParameter _FirstName_W = null;
			private WhereParameter _MYINTEGER_W = null;
			private WhereParameter _MYINT_W = null;

			public void WhereClauseReset()
			{
				_EmployeeID_W = null;
				_LastName_W = null;
				_FirstName_W = null;
				_MYINTEGER_W = null;
				_MYINT_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
		
			
		
		protected override IDbCommand GetInsertCommand()
		{
			SQLiteCommand cmd = new SQLiteCommand();
			cmd.CommandType = CommandType.Text;
			cmd.CommandText =
				@"INSERT INTO [Employees]
			(
				[LastName],
				[FirstName],
				[MYINTEGER],
				[MYINT]
			)
			VALUES
			(
				@LastName,
				@FirstName,
				@MYINTEGER,
				@MYINT
			)";

			CreateParameters(cmd);
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
			SQLiteCommand cmd = new SQLiteCommand();
			cmd.CommandType = CommandType.Text;
			cmd.CommandText = 
				@"UPDATE [Employees] SET 
				[LastName]=@LastName,
				[FirstName]=@FirstName,
				[MYINTEGER]=@MYINTEGER,
				[MYINT]=@MYINT
			WHERE
				[EmployeeID]=@EmployeeID";

			CreateParameters(cmd);
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
			SQLiteCommand cmd = new SQLiteCommand();
			cmd.CommandType = CommandType.Text;
			cmd.CommandText =
				@"DELETE FROM [Employees] 
			WHERE
				[EmployeeID]=@EmployeeID";

	
			SQLiteParameter p;
			p = cmd.Parameters.Add(Parameters.EmployeeID);
			p.SourceColumn = ColumnNames.EmployeeID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SQLiteCommand cmd)
		{
			SQLiteParameter p;
		
			p = cmd.Parameters.Add(Parameters.EmployeeID);
			p.SourceColumn = ColumnNames.EmployeeID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.LastName);
			p.SourceColumn = ColumnNames.LastName;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.FirstName);
			p.SourceColumn = ColumnNames.FirstName;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.MYINTEGER);
			p.SourceColumn = ColumnNames.MYINTEGER;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.MYINT);
			p.SourceColumn = ColumnNames.MYINT;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}		
		
	
	}
}


